(function() {var implementors = {};
implementors['crypto'] = ["<a class='stability Experimental' title='Experimental'></a>impl&lt;A: <a class='trait' href='crypto/sbuf/trait.Allocator.html' title='crypto::sbuf::Allocator'>Allocator</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a>&lt;<a class='struct' href='http://doc.rust-lang.org/curve41417/fe/struct.FieldElem.html' title='curve41417::fe::FieldElem'>FieldElem</a>&lt;A&gt;&gt; for <a class='struct' href='http://doc.rust-lang.org/curve41417/fe/struct.FieldElem.html' title='curve41417::fe::FieldElem'>FieldElem</a>&lt;A&gt;","<a class='stability Experimental' title='Experimental'></a>impl&lt;A: <a class='trait' href='crypto/sbuf/trait.Allocator.html' title='crypto::sbuf::Allocator'>Allocator</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a>&lt;<a class='struct' href='crypto/curve41417/ed/struct.GroupElem.html' title='crypto::curve41417::ed::GroupElem'>GroupElem</a>&lt;A&gt;&gt; for <a class='struct' href='crypto/curve41417/ed/struct.GroupElem.html' title='crypto::curve41417::ed::GroupElem'>GroupElem</a>&lt;A&gt;","<a class='stability Experimental' title='Experimental'></a>impl&lt;A: <a class='trait' href='crypto/sbuf/trait.Allocator.html' title='crypto::sbuf::Allocator'>Allocator</a>&gt; <a class='trait' href='http://doc.rust-lang.org/nightly/core/ops/trait.Neg.html' title='core::ops::Neg'>Neg</a>&lt;<a class='struct' href='crypto/curve41417/sc/struct.ScalarElem.html' title='crypto::curve41417::sc::ScalarElem'>ScalarElem</a>&lt;A&gt;&gt; for <a class='struct' href='crypto/curve41417/sc/struct.ScalarElem.html' title='crypto::curve41417::sc::ScalarElem'>ScalarElem</a>&lt;A&gt;",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
